image: python:3.9

stages:
  - prepare
  - lint

before_script:
  - python --version; pip --version
  - pip install virtualenv
  - virtualenv modeling_venv
  - source modeling_venv/bin/activate
  - pip install -r requirements_dev.txt

run_linters:
  stage: lint
  script: flake8 .
